---
title: "[Clean Code]클린코드 7장 예외 처리"
tags: [Book]
toc: true
widgets:
  - type: toc
    position: left
  - type: categories
    position: right
cover: /img/clean_code.jpeg
date: 2022-02-05 12:11:40
categories: [Book]
---

</pre>
<!--more-->

<!--more-->

## **7장 예외 처리**

🔖 `읽은 범위` : 6장, 객체와 자료 구조 ~ 7장, 예외 처리

---

### **1. 예외 처리 방식**

오류 코드를 리턴하지 말고 예외를 던져라

#### `try - catch로 예외처리`

```java
public class DeviceController {
    // ...

    public void sendShutDown() {
        try {
            tryToShutDown();
        } catch (DeviceShutDownError e) {
            logger.log(e);
        }
    }

    private void tryToShutDown() throws DeviceShutDownError {
        DeviceHandle handle = getHandle(DEV1);
        DeviceRecord record = retrieveDeviceRecord(handle);

        pauseDevice(handle);
        clearDeviceWorkQueue(handle);
        closeDevice(handle);
    }

    private DeviceHandle getHandle(DeviceId id) {
        // ...
        throw new DeviceShutDownError("Invalid handle for: " + id.toString());
        // ...
    }

    // ...
}
```

---

### **2. Unchecked Exception을 사용하라**

`checked Exception이 나쁜 이유`

- 특정 메소드에서 checked exception을 throw하고 상위 메소드에서 그 exception을 catch 한다면, 모든 중간단계 메소드에 exception을 throws해야한다.
- 이는 OCP(개방 폐쇄 원칙)위배이다. 상위 메소드에서 하위 레벨 메소드의 디테일에 대해 알아야하기 때문이다.
- 필요한 경우 checked exception을 사용해야 되지만, 일반적인 경우 득보다 실이 많다.
- 파이썬, C#, C++, 루비는 checked exception을 지원하지 않음에도 안정적인 소프트웨어를 구현하기에 무리가 없다.

---

### **3. Exception 잘 쓰기**

#### `예외에 메시지를 담아라`

- 오류가 발생한 원인과 위치를 찾기 쉽도록, 예외를 던질 때는 전후 상황을 충분히 덧붙인다.
- 실패한 연산 이름과 유형 등 정보를 담아 예외를 던진다.

#### `exception wrapper`

예외를 감싸는 클래스를 만든다

- port.open() 시 발생하는 checked exception들을 감싸도록 port를 가지는 LocalPort 클래스를 만든다.
- port.open()이 던지는 checked 들을 하나의 PortDeviceFailure exception으로 감싸서 던진다.

나쁜 예

```java
ACMEPort port = new ACMEPort(12);
try {
  port.open();
} catch (DeviceResponseException e) {
  reportPortError(e);
  logger.log("Device response exception", e);
} catch (ATM1212UnlockedException e) {
  reportPortError(e);
  logger.log("Unlock exception", e);
} catch (GMXError e) {
  reportPortError(e);
  logger.log("Device response exception", e);
}
```

좋은 예

```java
LocalPort port = new LocalPort(12);
try {
  port.open();
} catch (PortDeviceFailure e) {
  reportError(e);
  logger.log(e.getMessage(), e);
} finally {
  ...
}

public class LocalPort {
    private ACMEPort innerPort;

    public LocalPort(int portNumber) {
        innerPort = new ACMEPort(portNumber);
    }

    public void open() {
        try {
            innerPort.open();
        } catch (DeviceResponseException e) {
            throw new PortDeviceFailure(e);
        } catch (ATM1212UnlockedException e) {
            throw new PortDeviceFailure(e);
        } catch (GMXError e) {
            throw new PortDeviceFailure(e);
        }
    }

    // ..
}
```

---

### **4. 실무 예외 처리 패턴**

#### `getOrElse`

예외 대신 기본 값을 리턴한다.

- null이 아닌 기본 값
- 도메인에 맞는 기본 값

##### `null이 아닌 기본 값 예제`

나쁜 예

```java
List<Employee> employees = getEmployees();
if (employee != null) {
    for(Employee e : employees) {
        totalPay += e.getPay();
    }
}
```

- null을 리턴한다면, 이후 코드에서도 모두 null 체크가 있어야 한다.

좋은 예

```java
List<Employee> employees = getEmployees();
for(Employee e : employees) {
    totalPay += e.getPay();
}

public List<Employee> getEmployees() {
    if ( /*.. 직원이 없을 경우 .. */) {
        return Collections.emptyList();
    }
}
```

- 복수 형의 데이터를 가져올 떄는 데이터가 없음을 의미하는 컬렉션을 리턴하면 된다.
- null 보다 size가 0인 컬렉션이 훨씬 안전하다.

##### `도메인에 맞는 기본 값 예제`

나쁜 예

```java
UserLevel userLevel = null;
try {
  User user = user.Repository.findByUserId(userId);
  userLevel = user.getUserLevel();
} catch (UserNotfoundException e) {
  userLevel = UserLevel.BASIC;
}
```

- 호출부에서 예외 처리를 통해 userLevel 값을 처리한다.
- 코드를 계속 읽어나가면서 논리적인 흐름이 끊긴다.

좋은 예

```java
public class UserService {
  public static final UserLevel USER_BASIC_LEVEL = UsrLevel.BASIC;

  public UserLevel getUserLevelOrdefault(Long userId) {
    try {
      User user = userRepository.findByUserId(userId);
      return user.getUserLevel();
    } catch(UserNotFoundException e) {
      return USER_BASIC_LEVEL;
    }
  }
}

UserLevel userLevel = userService.getuserLevelOrDefault(userId);
```

호출부 - 단순해짐

- 예외 처리를 데이터를 제공하는 쪽에서 처리해 호출부 코드가 심플해진다.
- 코드를 읽어가며 논리적인 흐름이 끊기지 않는다.
- 도메인에 맞는 기본 값을 도메인 서비스에서 관리한다.

#### `getOrElseThrow`

##### `(기본 값이 없다면) null 대신 예외를 던진다`

나쁜 예

```java
User user = userRepository.findByUseId(userId);
if (user != null) {
  // user를 이용한 처리
}
```

- user를 사용하는 쪽에서 매번 체크를 해야한다.
- 가독성 뿐만 아니라 안정성도 떨어진다.
- null 체크가 빠진 부분이 발생할 수 있다.

좋은 예

```java
public class UserService {
  public static final UserLevel USER_BASIC_LEVEL = UsrLevel.BASIC;

  public User getUserOrElseThrow(Long userId) {
    User user = userRepository.findByUserId(userId);
    if (user == null) {
      throw new IllegalArgumentException("User is not found. userId = " + userId)
    }
    return user;
    }
  }

User user = user.Service.getUserOrElseThrow(userId);
```

- 데이터를 제공하는 쪽에서 null 체크를 하여, 데이터가 없는 경우엔 예외를 던진다.
- 호출부에서 매번 null 체크를 할 필요 없이 안전하게 데이터를 사용할 수 있다.
- 호출부의 가독성이 올라간다.

##### `파라미터의 null을 점검하라`

나쁜 예

```java
public class MetricsCalculator {
  public double xProjection(Point p1, Point p2) {
    return (p2.x - p1.x) * 1.5;
  }
}

// calculator.xProjection(null, new Point(12, 13));
// NullPointerException 발생
```

- null을 리턴하는 것도 나쁘지만 null을 메서드로 넘기는 것은 더 나쁘다.
- null을 메서드의 파라미터로 넣어야 하는 API를 사용하는 경우가 아니면 null을 메서드로 넘기지 마라.

좋은 예 - throw new ~ 사용

```java
public class MetricsCalculator {
  public double xProjection(Point p1, Point p2) {
    if (p1 == null || p2 == null) {
      throw InvalidArgumentException("Invalid argument for MetricsCalculator.xProjection");
    }
    return (p2.x - p1.x) * 1.5;
  }
}
```

- null이 들어오면 unchecked exception을 발생시킨다.
- 실무에서는 assert보다 예외를 던지는 방법을 훨씬 많이 사용한다.

좋은 예 - assert 사용

```java
public class MetricsCalculator {
  public double xProjection(Point p1, Point p2) {
    assert p1 != null : "p1 should not be null";
    assert p2 != null : "p2 should not be null";
    return (p2.x - p1.x) * 1.5;
  }
}
```

##### `실무에서는 보통 자신의 예외를 정의한다`

```java
public class MyProjectException extends RuntimeException {
  private MyErrorCode errorCode;
  private String errorMessage;

  public MyProjectException(MyErrorCode errorCode) {
    //
  }

  public MyProjectException(MyErrorCode errorCode, String errorMessage) {
    //
  }
}

public enum MyErrorCode {
  private String defaultErrorMessage;

  INVALID_REQUEST("잘못된 요청입니다."),
  DUPLICATED_REQUEST("기존 요청과 중복되어 처리할 수 없습니다."),
  // ...
  INTERNAL_SERVER_ERROR("처리 중 에러가 발생했습니다.");
}

//호출부
if (request.getUserName() == null) {
  throw new MyProjectException(ErrorCode.INVALID_REQUEST, "userName is null");
}
```

- 에러 로그에서 stacktrace 해봤을 때 우리가 발생시킨 예외라는 것을 바로 인지할 수 있다.
- 다른 라이브러리에서 발생한 에러와 섞이지 않는다. 우리도 IllegalArgumentException을 던지는 것보다 우리 예외로 던지는게 어느 부분에서 에러가 났는지 파악하기에 용이하다.
- 우리 시스템에서 발생한 에러의 종류를 나열할 수 있다.
